In [52]:
import pandas as pd
import pyarrow.feather as pq
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

<h1>Sampling in Python</h1>

<img src="https://hotcubator.com.au/wp-content/uploads/2020/07/Copy-of-Social-Business-1.png">

In [53]:
coffee_ratings_full = pd.read_feather('data/coffee_ratings_full.feather')
coffee_ratings_full.sample(10)

,total_cup_points,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
756,82.17,Arabica,ipanema coffees,Brazil,fazenda capoeirnha,007/16C,dry mill,002/1660/0105,ipanema coffees,934,...,Green,5.0,"August 16th, 2017",Brazil Specialty Coffee Association,3297cfa4c538e3dd03f72cc4082c54f7999e1f9d,8900f0bf1d0b2bafe6807a73562c7677d57eb980,m,934.00,934.00,934.00
475,83.17,Arabica,nucoffee,Brazil,olhos d'agua,None,None,None,None,900m,...,None,2.0,"October 27th, 2012",NUCOFFEE,567f200bcc17a90070cb952647bf88141ad9c80c,aa2ff513ffb9c844462a1fb07c599bce7f3bb53d,m,900.00,900.00,900.00
866,81.75,Arabica,armando luis pohlenz martinez,Mexico,None,None,finca custepec,2676,beneficio custepec s.a. de c.v.,1550,...,Green,14.0,"August 30th, 2013",AMECAFE,59e396ad6e22a1c22b248f958e1da2bd8af85272,0eb4ee5b3f47b20b049548a2fd1e7d4a2b70d0a7,m,1550.00,1550.00,1550.00
646,82.58,Arabica,exportadora de cafe condor s.a,Colombia,various,None,trilladora boananza,3-68-0160,exportadora de cafe condor s.a,1750 msnm,...,Blue-Green,3.0,"April 16th, 2014",Almacafé,e493c36c2d076bf273064f7ac23ad562af257a25,70d3c0c26f89e00fdae6fb39ff54f0d2eb1c38ab,m,1750.00,1750.00,1750.00
214,84.17,Arabica,juan luis alvarado romero,Guatemala,santo tomas pachuj,11/752/01,beneficio palinsa,11/752/01,cafcom,1565,...,Green,10.0,"June 1st, 2017",Asociacion Nacional Del Café,b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53,724f04ad10ed31dbb9d260f0dfd221ba48be8a95,m,1565.00,1565.00,1565.00
544,82.92,Arabica,kawacom uganda ltd,Uganda,sipi organic coffee project,None,kawacom,0,kawacom uganda ltd,1400-1900,...,Green,0.0,"June 27th, 2015",Uganda Coffee Development Authority,188fe373b511e21f614564bf86aa4774270d8e04,b7614767a5343729bbde3a2777c60ce836aed928,m,1400.00,1900.00,1650.00
1197,79.08,Arabica,racafe & cia s.c.a,None,None,None,None,3-37-1980,None,None,...,None,3.0,"February 29th, 2012",Almacafé,e493c36c2d076bf273064f7ac23ad562af257a25,70d3c0c26f89e00fdae6fb39ff54f0d2eb1c38ab,m,NaN,NaN,NaN
58,85.83,Arabica,juan luis alvarado romero,Guatemala,finca el limon,None,beneficio serben,11-853-155,unicafe,4650,...,Bluish-Green,1.0,"June 5th, 2013",Asociacion Nacional Del Café,b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53,724f04ad10ed31dbb9d260f0dfd221ba48be8a95,ft,1417.32,1417.32,1417.32
629,82.67,Arabica,kona pacific farmers cooperative,United States (Hawaii),None,None,None,None,None,None,...,None,0.0,"September 19th, 2012",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,ft,NaN,NaN,NaN
36,86.25,Arabica,kona pacific farmers cooperative,United States (Hawaii),None,None,None,220452,kona pacific farmers cooperative,None,...,None,4.0,"April 6th, 2013",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,ft,NaN,NaN,NaN

In [54]:
attrition = pd.read_feather("data/attrition.feather")
attrition.sample(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
173,32,0.0,Non-Travel,976,Sales,26,Master,Marketing,High,Male,...,Excellent,Low,0,4,2,Better,3,2,2,2
45,27,0.0,Travel_Rarely,618,Research_Development,4,Bachelor,Life_Sciences,Medium,Female,...,Excellent,High,0,1,2,Better,1,1,0,0
858,32,0.0,Travel_Rarely,495,Research_Development,10,Bachelor,Medical,High,Male,...,Outstanding,Medium,0,10,5,Best,5,2,0,0
522,41,1.0,Travel_Rarely,1102,Sales,1,College,Life_Sciences,Medium,Female,...,Excellent,Low,0,8,0,Bad,6,4,0,5
107,35,0.0,Travel_Frequently,636,Research_Development,4,Master,Other,Very_High,Male,...,Excellent,Medium,1,2,2,Best,2,2,2,2
1257,38,0.0,Travel_Frequently,1394,Research_Development,8,Bachelor,Medical,Very_High,Female,...,Excellent,High,1,20,3,Better,20,11,0,7
247,26,1.0,Travel_Rarely,1449,Research_Development,16,Master,Medical,Low,Male,...,Excellent,Very_High,1,5,2,Better,3,2,0,2
592,33,0.0,Travel_Frequently,1111,Sales,5,Below_College,Life_Sciences,Medium,Male,...,Excellent,Low,0,8,2,Best,5,4,1,2
129,21,1.0,Travel_Frequently,756,Sales,1,Below_College,Technical_Degree,Low,Female,...,Excellent,High,0,3,3,Better,3,2,1,2
131,31,0.0,Travel_Rarely,408,Research_Development,9,Master,Life_Sciences,High,Male,...,Excellent,Very_High,0,3,5,Better,2,2,2,2

In [55]:
spotify_2000_2020 = pd.read_feather("data/spotify_2000_2020.feather")
spotify_2000_2020.sample(10)

,acousticness,artists,danceability,duration_ms,duration_minutes,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo,valence,year
20508,0.281000,"['Futuristic', 'NF']",0.754,249168.0,4.152800,0.823,1.0,7whWjytFNIYch6MAnIWZTS,0.000000,6.0,0.1070,-5.502,0.0,Epiphany (feat. NF),57.0,2017-12-25,0.2200,125.932,0.548,2017.0
24039,0.057800,['Arcade Fire'],0.616,315200.0,5.253333,0.682,0.0,2UWdUez9MB9yzL7Y81Mcip,0.024100,6.0,0.3420,-6.148,0.0,The Suburbs,69.0,2010,0.0265,117.780,0.528,2010.0
23018,0.000548,['Gary Glitter'],0.752,180600.0,3.010000,0.218,0.0,63W11KVHDOpSlh3XMQ7qMg,0.788000,11.0,0.0699,-15.177,0.0,Rock And Roll Part II,65.0,2000-01-01,0.0653,130.068,0.552,2000.0
14068,0.055600,['Halsey'],0.500,165213.0,2.753550,0.633,0.0,36dfGEKTGHxLmdNIYr0VTi,0.000000,9.0,0.3110,-6.251,0.0,I Walk The Line,55.0,2015-08-28,0.0414,119.901,0.195,2015.0
33019,0.371000,['Niall Horan'],0.443,223044.0,3.717400,0.533,1.0,39jXnbACjiaiTwwhsr5sY5,0.000000,0.0,0.1280,-6.549,1.0,Too Much To Ask,73.0,2017-10-20,0.0396,77.342,0.201,2017.0
40878,0.000506,['Nipsey Hussle'],0.678,209427.0,3.490450,0.530,1.0,5IQo8cHllhsjC0Rl1f2lCQ,0.000001,6.0,0.0477,-10.319,0.0,4 in the Mornin,51.0,2013-10-22,0.3550,139.948,0.441,2013.0
23341,0.628000,['Jesús Adrián Romero'],0.490,327653.0,5.460883,0.510,0.0,6Z31l856yEwyJqSBe3qLZ4,0.000000,0.0,0.9670,-9.141,1.0,Sumérgeme,66.0,2003-05-07,0.0368,90.307,0.197,2003.0
35142,0.282000,['Sam Smith'],0.535,221596.0,3.693267,0.382,1.0,59ljpSFcgtfWJKS3vqG27R,0.000011,4.0,0.0865,-9.465,0.0,Pray,63.0,2017-11-03,0.0426,87.801,0.147,2017.0
5570,0.825000,['Daft Punk'],0.712,322147.0,5.369117,0.500,0.0,3ctALmweZBapfBdFiIVpji,0.314000,9.0,0.1060,-11.948,0.0,The Game of Love,58.0,2013-05-17,0.0338,90.039,0.682,2013.0
3177,0.793000,['Cody Jinks'],0.559,188613.0,3.143550,0.122,0.0,2ibQ2ntPan6aZ09fbc5juH,0.000001,5.0,0.3180,-11.983,1.0,Less Wise,46.0,2010-06-28,0.0701,117.455,0.335,2010.0